name: crear un artefacto desde el api de la NASA

on:
  push:
    branches:
      - main

jobs:
  read-dates:
    runs-on: ubuntu-latest
    outputs:
      dates: ${{ steps.get_dates.outputs.dates }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Leer el JSON del repositorio
        id: get_dates
        run: |
          DATES=$(jq -c '.dates' dates.json)
          echo "dates=$DATES" >> $GITHUB_ENV
          echo "dates=$DATES" >> $GITHUB_OUTPUT

  nasa-images:
    needs: read-dates
    runs-on: ubuntu-latest

    strategy:
      matrix:
        date: ${{ fromJson(needs.read-dates.outputs.dates) }}   

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Save NASA image from URL 
        uses: minituff/save-image@v1.4
        id: wakatime
        with:
          url: "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.API_KEY }}&date=${{ matrix.date }}"
          imagePath: 'img-${{ matrix.date }}.jpg'

      - name: Generar artefacto por imagen ${{ matrix.date }}
        uses: actions/upload-artifact@v4
        with:
          name: img-${{ matrix.date }}
          path: img-${{ matrix.date }}.jpg
