name: Export Images from NASA API

on:
  push:
    branches:
      - main

jobs:
  read-dates:
    runs-on: ubuntu-latest
    outputs:
      dates: ${{ steps.get_dates.outputs.dates }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load Dates JSON
        id: get_dates
        run: |
          DATES=$(cat dates.json | jq -r '.dates | join(",")')
          echo "::set-output name=dates::${DATES}"

  nasa-images:
    needs: read-dates
    runs-on: ubuntu-latest

    strategy:
      matrix:
        date: ${{ fromJson(env.dates) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Image
        uses: githubocto/requests-action@v2
        id: get-nasa-image
        with:
          url: "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.API_KEY }}&date=${{ matrix.date }}"
          method: GET

      - name: Download Image
        run: |
          URL=$(echo ${{ steps.get-nasa-image.outputs.response }} | jq -r '.url')
          curl -s $URL --output img-${{ matrix.date }}.jpg

      - name: Upload JSON Artifact for ${{ matrix.date }}
        uses: actions/upload-artifact@v3
        with:
          name: img-${{ matrix.date }}
          path: img-${{ matrix.date }}.jpg
