name: Export Images from NASA API

on:
  push:
    branches:
      - main

jobs:
  read-dates:
    runs-on: ubuntu-latest
    outputs:
      dates: ${{ steps.get_dates.outputs.dates }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: leer el JSON
        id: get_dates
        run: |
          DATES=$(cat dates.json | jq -c '.dates' dates.json)
          echo "::set-output name=dates::${DATES}"

  nasa-images:
    needs: read-dates
    runs-on: ubuntu-latest

    strategy:
      matrix:
        date: ${{ fromJson(needs.read-dates.outputs.dates) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: obtener imagen de la nasa
        uses: fjogeleit/http-request-action@v1
        id: get-from-image
        with:
          url: "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.API_KEY }}&date=${{ matrix.date }}"
          method: GET

      - name: Descargar imagen de la NASA
        run: |
          URL=$(echo "${{ steps.get-from-image.outputs.response }}" | jq -r '.url') # Cambié get-nasa-image a get-from-image
          echo "URL de la imagen: $URL" # Imprimir para depuración
          curl -s "$URL" --output img-${{ matrix.date }}.jpg

      - name: Upload JSON Artifact for ${{ matrix.date }}
        uses: actions/upload-artifact@v3
        with:
          name: img-${{ matrix.date }}
          path: img-${{ matrix.date }}.jpg
