name: Export Images from NASA API

on:
  push:
    branches:
      - main

jobs:
  read-dates:
    runs-on: ubuntu-latest
    outputs:
      dates: ${{ steps.get_dates.outputs.dates }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Leer el JSON
        id: get_dates
        run: |
          DATES=$(jq -c '.dates' dates.json)
          echo "dates=$DATES" >> $GITHUB_ENV
          echo "dates=$DATES" >> $GITHUB_OUTPUT

  nasa-images:
    needs: read-dates
    runs-on: ubuntu-latest

    strategy:
      matrix:
        date: ${{ fromJson(needs.read-dates.outputs.dates) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obtener imagen de la NASA
        uses: fjogeleit/http-request-action@v1
        id: get-from-image
        with:
          url: "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.API_KEY }}&date=${{ matrix.date }}"
          method: GET


      - name: Descargar imagen de la NASA
        run: |
            URL=$(curl -s "https://api.nasa.gov/planetary/apod?api_key=${{ secrets.API_KEY }}&date=${{ matrix.date }}" \
            | jq -r '.url')
            
            curl -s "$URL" --output "img-${{ matrix.date }}.jpg"

      - name: Upload JSON Artifact for ${{ matrix.date }}
        uses: actions/upload-artifact@v4
        with:
          name: img-${{ matrix.date }}
          path: img-${{ matrix.date }}.jpg

