name: export images from NASA API
on:
  push:
    branches:
      - main
jobs:
  images:
    name: export_image
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout_repository
        uses: actions/checkout@v4

      - name: load dates JSON
        id: load-dates
        run: |
          DATES=$(cat dates.json | jq -r '.dates[]')
          echo "DATE=${DATE}">> $GITHUB_ENV

      - name: parallel for dates
        uses: actions/cache@v4
        with:
          path: dates.json
          key: nasa-images-${{runner.os}}-${{hashFiles('**/dates.json')}}
        id: nasa-images

      - name: get images from nasa with date
        if: ${{steps.cache-nasa-images.outputs.cache-hit !='true'}}
        run: >
          for DATES in $DATES; do
          uses: githubocto/requests-action@v2
          id: get-nasa-image
          with:
            url: "https://api.nasa.gov/planetary/apod?api_key=${{secrets.API_KEY}}&date=$DATES"
            method: GET
      - name : extract imagesfrom reponse
        run: |
          RESPONSE=$(cat ${{ steps.get-nasa-image.outputs.response }})
          URL=$(echo $RESPONSE | jq -r '.url')
          CACHE_FILE="cache/nasa_image_$DATES.json"
          echo $RESPONSE > $CACHE_FILE

            curl -s $URL --output img-$DATES.jpg
          done

      - name: Upload_JSON_artifact_for $DATES
        uses: actions/upload-artifact@v3
        with:
          name: img-${DATES}
          path: img-${DATES}.jpg
