name: json-to-file

on:
  push:
    branches:
      - main
 
jobs:
  test:
    name: json to file
    runs-on: ubuntu-latest
    steps: 
    - uses: devops-actions/json-to-file@v1.0.0
      with:
        json: |
          '{"name": "pipelines","activity": 3,"module": 2,"isRequired": false}'
        filename: 'archivo.json'

    - uses: actions/upload-artifact@v4
      with:
        name: archivo.json report
        path: archivo.json